### ISSUE TITLE
Postgres RDS increased Resource Usage after enabling IAM Authentication

### ISSUE THREAD

**Issue by lukaalba** [aws/aws-advanced-jdbc-wrapper#1015]
### Describe the bug

I am currently switching the authentication method for a Java Service from password to iam authentication. After using iam, the cpu and disk usage on the rds instance increased significantly which was not an issue at all while using a password. Furthermore it seems, that after a while, the service is not able to stay connected to the database, logging the following stack trace:

```
"name":"org.springframework.jms.listener.adapter.ListenerExecutionFailedException","cause":{"commonElementCount":10,"localizedMessage":"Could not open JPA EntityManager for transaction","message":"Could not open JPA EntityManager for transaction","name":"org.springframework.transaction.CannotCreateTransactionException","cause":{"commonElementCount":10,"localizedMessage":"Unable to acquire JDBC Connection [HikariPool-1 - Connection is not available, request timed out after 30000ms (total=0, active=0, idle=0, waiting=0)] [n/a]","message":"Unable to acquire JDBC Connection [HikariPool-1 - Connection is not available, request timed out after 30000ms (total=0, active=0, idle=0, waiting=0)] [n/a]","name":"org.hibernate.exception.JDBCConnectionException","cause":{"commonElementCount":10,"localizedMessage":"HikariPool-1 - Connection is not available, request timed out after 30000ms (total=0, active=0, idle=0, waiting=0)","message":"HikariPool-1 - Connection is not available, request timed out after 30000ms (total=0, active=0, idle=0, waiting=0)","name":"java.sql.SQLTransientConnectionException","cause":{"commonElementCount":1,"localizedMessage":"The connection attempt failed.","message":"The connection attempt failed.","name":"org.postgresql.util.PSQLException","cause":{"commonElementCount":1,"name":"java.io.EOFException","extendedStackTrace":"java.io.EOFException: null
at org.postgresql.core.PGStream.receiveChar(PGStream.java:469) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:683) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.3.jar!/:42.7.3]
at software.amazon.jdbc.DriverConnectionProvider.connect(DriverConnectionProvider.java:133) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:203) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:191) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:373) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$0(ConnectionPluginManager.java:263) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:240) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$1(ConnectionPluginManager.java:263) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:268) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.connectInternal(IamAuthConnectionPlugin.java:171) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.connect(IamAuthConnectionPlugin.java:114) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:373) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:267) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:240) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:267) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:230) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:370) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:160) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:105) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.Driver.connect(Driver.java:176) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) ~[HikariCP-5.1.0.jar!/:?]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]\n"},"extendedStackTrace":"org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.3.jar!/:42.7.3]
at software.amazon.jdbc.DriverConnectionProvider.connect(DriverConnectionProvider.java:133) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:203) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:191) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:373) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$0(ConnectionPluginManager.java:263) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:240) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$1(ConnectionPluginManager.java:263) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:268) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.connectInternal(IamAuthConnectionPlugin.java:171) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.connect(IamAuthConnectionPlugin.java:114) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:373) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:267) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:240) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:267) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:230) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:370) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:160) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:105) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.Driver.connect(Driver.java:176) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) ~[HikariCP-5.1.0.jar!/:?]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]\nCaused by: java.io.EOFException
at org.postgresql.core.PGStream.receiveChar(PGStream.java:469) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:683) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.3.jar!/:42.7.3]
at software.amazon.jdbc.DriverConnectionProvider.connect(DriverConnectionProvider.java:133) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:203) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:191) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:373) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$0(ConnectionPluginManager.java:263) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:240) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$1(ConnectionPluginManager.java:263) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:268) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.connectInternal(IamAuthConnectionPlugin.java:171) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.connect(IamAuthConnectionPlugin.java:114) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:373) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:267) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:240) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:267) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:230) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:370) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:160) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:105) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at software.amazon.jdbc.Driver.connect(Driver.java:176) ~[aws-advanced-jdbc-wrapper-2.3.6.jar!/:?]
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) ~[HikariCP-5.1.0.jar!/:?]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]\n\t... 1 more\n"},"extendedStackTrace":"java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms (total=0, active=0, idle=0, waiting=0)
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-5.1.0.jar!/:?]
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:127) ~[HikariCP-5.1.0.jar!/:?]
at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:143) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:273) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:281) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:232) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-6.5.2.Final.jar!/:6.5.2.Final]
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:176) ~[spring-orm-6.1.8.jar!/:6.1.8]
at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:420) ~[spring-orm-6.1.8.jar!/:6.1.8]
at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:532) ~[spring-tx-6.1.8.jar!/:6.1.8]
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:405) ~[spring-tx-6.1.8.jar!/:6.1.8]
at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:617) ~[spring-tx-6.1.8.jar!/:6.1.8]
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386) ~[spring-tx-6.1.8.jar!/:6.1.8]
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.1.8.jar!/:6.1.8]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.8.jar!/:6.1.8]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) ~[spring-aop-6.1.8.jar!/:6.1.8]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720) ~[spring-aop-6.1.8.jar!/:6.1.8]
at de.db.sab.fzofv.fahrtereignis.ermittlung.adapter.FahrzeugortungV2Consumer$$SpringCGLIB$$0.handleMessage(<generated>) ~[!/:?]
at de.db.sab.fzofv.fahrtereignis.support.amqp.AmqpMessageReceiver.retrieveMessage(AmqpMessageReceiver.java:27) ~[!/:?]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-6.1.8.jar!/:6.1.8]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-6.1.8.jar!/:6.1.8]
at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:110) ~[spring-jms-6.1.8.jar!/:6.1.8]\nCaused by: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar!/:42.7.3]
at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.3.jar!/:42.7.3]
```

During that time, the RDS instance logs the following messages:

```
2024-05-29 07:50:55 UTC:10.107.226.35(45874):readonly@databasename:[8185]:LOG: pam_authenticate failed: Permission denied
2024-05-29 07:50:55 UTC:10.107.226.35(45874):readonly@databasename:[8185]:FATAL: canceling authentication due to timeout
```

I am confused, because other services migrated to IAM Authentication work perfectly fine without any error messages or higher resource usage on RDS side. The only difference is that this services operates in two different modes which are deployed at the same time, leading to two different services connecting to the same RDS instance.

Thanks in advance!

### Expected Behavior

Switching to IAM Authentication works without any side effects or error messages

### What plugins are used? What other connection properties were set?

iam

### Current Behavior

IAM Authentication stops working after a while (~30 minutes).

RDS resource usage increases:

- CPU Usage from usually ~10% to 30%
- total IOPS from ~250 to over 800

### Reproduction Steps

Spring Boot 3.3 with HicariCP

datasource configuration:

```
spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://${spring.datasource.host}/databasename?sslmode=${spring.datasource.sslMode}&sslfactory=${spring.datasource.sslfactory}
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      data-source-properties:
        wrapperPlugins: iam
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
```

RDS instance type db.t4g.micro, Postgresql 16.1

### The AWS Advanced JDBC Driver version used

2.3.6

### JDK version used

17

### Operating System and version

wolfi os / chainguard-jdk container image

**Comment by aaronchung-bitquill** [comment]
Hi @lukaalba 

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

In the meantime, I have a few clarifying questions

- Are the other services that have migrated to IAM Authentication, also using Spring Boot 3.3 with HikariCP, and using the IAM authentication plugin? 
- Can you elaborate on the "two different modes"?
- The service that operates in two different modes, are they deployed on same instance/machine?
- Are there any other properties or configurations on the datasource? (ex. HikariCP configurations)
- Do you have any examples of how you are using the datasource and making queries? 
- What type of queries are you making, and with what frequency/load? 

Thank you!

**Comment by lukaalba** [comment]
Hi @aaronchung-bitquill,

thanks for you reply. I've updated the original issue with the requested details. All services including the ones already migrated to IAM authentication running with Spring Boot 3.3. and HikariCP

**Comment by lukaalba** [comment]
After further investigation and contacting the AWS Support, it seems that the issue is not related to the wrapper but to our instance type. Thanks for your help so far, the issue can be closed
